version: '3'

tasks:

  check:
    desc: Standard linting of shell scripts
    cmds:
      - find scripts -type f -name '*.sh' | xargs shellcheck

  clean:
    desc: Clean git repo
    cmds:
      - git clean -fdX
